---
# 🟢 PARTIE EXTRACT

### Ex E1 ⭐ — Explorer les sources
Affichez pour chaque DataFrame : shape, colonnes, dtypes, et les 3 premières lignes.

In [1]:
import pandas as pd
import numpy as np

fichiers_csv = ["clients.csv", "commandes_Q1.csv", "commandes_Q2.csv", "produits.csv"]

for i in fichiers_csv:
    df = pd.read_csv(i)
    print(f"\nNom du fichier : {i}")
    print("Lignes, colonnes :", df.shape)
    print("Colonnes :", list(df.columns))
    print(df.dtypes)
    display(df.head(3))

Nom du fichier : clients.csv
Lignes, colonnes : (515, 9)
Colonnes : ['client_id', 'nom', 'email', 'ville', 'region', 'segment', 'date_inscription', 'ca_historique', 'actif']
client_id            object
nom                  object
email                object
ville                object
region               object
segment              object
date_inscription     object
ca_historique       float64
actif                  bool
dtype: object

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CLI0001,Client_1,client1@email.fr,Toulouse,Auvergne-RA,Startup,2021-02-01,129.67,True
1,CLI0002,Client_2,client2@email.fr,Lyon,Nouvelle-Aquitaine,Particulier,2022-08-11,42431.54,False
2,CLI0003,Client_3,client3@email.fr,Nantes,Occitanie,PME,2023-11-17,6895.77,True

Nom du fichier : commandes_Q1.csv
Lignes, colonnes : (3020, 10)
Colonnes : ['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire', 'montant_total', 'date_commande', 'statut', 'mode_paiement', 'region_livraison']
commande_id          object
client_id            object
produit_id           object
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande        object
statut               object
mode_paiement        object
region_livraison     object
dtype: object

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine

Nom du fichier : commandes_Q2.csv
Lignes, colonnes : (3220, 11)
Colonnes : ['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire', 'montant_total', 'date_commande', 'statut', 'moyen_paiement', 'region_livraison', 'devise']
commande_id          object
client_id            object
produit_id           object
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande        object
statut               object
moyen_paiement       object
region_livraison     object
devise               object
dtype: object

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,moyen_paiement,region_livraison,devise
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR
1,CMD-Q2-00002,CLI0346,PRD0106,1,52.42,52.42,2024-04-18,livrée,CB,PACA,EUR
2,CMD-Q2-00003,CLI0282,PRD0021,8,78.18,625.44,2024-05-05,annulée,CB,Occitanie,EUR

Nom du fichier : produits.csv
Lignes, colonnes : (152, 7)
Colonnes : ['produit_id', 'nom', 'categorie', 'prix_unitaire', 'stock', 'fournisseur', 'actif']
produit_id        object
nom               object
categorie         object
prix_unitaire    float64
stock              int64
fournisseur       object
actif               bool
dtype: object

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True
1,PRD0002,Produit_Inf_2,Informatique,135.96,102,MediaShop,True
2,PRD0003,Produit_Inf_3,Informatique,83.45,372,ElecPlus,False

### Ex E2 ⭐ — Détecter les différences entre Q1 et Q2
Trouvez les colonnes présentes dans Q2 mais absentes de Q1, et vice-versa.
Affichez les différences clairement.

In [2]:
csv_commande_Q1 =  "commandes_Q1.csv"
csv_commande_Q2 = "commandes_Q2.csv"

df_q1 = pd.read_csv(csv_commande_Q1)
df_q2 = pd.read_csv(csv_commande_Q2)

df_q1.head(1)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie

In [3]:
# Utilisation du set pour afficher les différences

cols_q1, cols_q2 = set(df_q1.columns), set(df_q2.columns)
print(f"Uniquement dans Q1 : {cols_q1 - cols_q2}")
print(f"Uniquement dans Q2 : {cols_q2 - cols_q1}")
print(f"Communes           : {cols_q1 & cols_q2}")

Uniquement dans Q1 : {'mode_paiement'}
Uniquement dans Q2 : {'devise', 'moyen_paiement'}
Communes           : {'prix_unitaire', 'commande_id', 'date_commande', 'montant_total', 'region_livraison', 'quantite', 'statut', 'produit_id', 'client_id'}

In [4]:
df_q2.head(1)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,moyen_paiement,region_livraison,devise
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR

In [5]:
#### Ce sont les colonnes moyen_paiement, mode_paiement et devise ####

### Ex E3 ⭐ — Harmoniser les colonnes
1. Renommez la colonne problématique dans Q2 pour qu'elle corresponde à Q1
2. Ajoutez la colonne manquante dans Q1 avec une valeur par défaut
3. Vérifiez que les deux DataFrames ont maintenant les mêmes colonnes

In [6]:
# 1. Renommez la colonne problématique dans Q2 pour qu'elle corresponde à Q1

df_q2 = df_q2.rename(columns={"moyen_paiement":"mode_paiement"})
df_q2.head(1)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR

In [7]:
# 2. Ajoutez la colonne manquante dans Q1 avec une valeur par défaut

df_q1["devise"] = "EUR"
df_q1.head(1)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR

In [8]:
# 3. Vérifiez que les deux DataFrames ont maintenant les mêmes colonnes

q1_q2 = [df_q1, df_q2]

for i in q1_q2:
    display(i.head(1))

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR

### Ex E4 ⭐ — Consolider avec pd.concat
1. Ajoutez une colonne `source` dans Q1 (`'Q1_2024'`) et Q2 (`'Q2_2024'`)
2. Concaténez Q1 et Q2 avec `pd.concat`
3. Vérifiez que le total de lignes est cohérent
4. Affichez la répartition des lignes par source

In [9]:
df_q1.shape

(3020, 11)

In [10]:
df_q2.shape

(3220, 11)

In [11]:
df_q1["source"] = "Q1_2024"
df_q2["source"] = "Q2_2024"

df_commandes = pd.concat([df_q1, df_q2], ignore_index=True)
df_commandes.shape

(6240, 12)

In [12]:
df_commandes['source'].value_counts()

source
Q2_2024    3220
Q1_2024    3020
Name: count, dtype: int64

### Ex E5 ⭐⭐ — Fonction extract()
Encapsulez tout dans une fonction `extract(q1_path, q2_path, clients_path, produits_path) -> dict`
qui retourne un dictionnaire avec les 4 DataFrames harmonisés et consolidés.
La fonction doit afficher des logs à chaque étape.

In [13]:
import pandas as pd
import logging 

# Configuration de base :
logging.basicConfig(level=logging.INFO,format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",datefmt="%H:%M:%S",force=True,)
logger = logging.getLogger("ETL")

q1_path= "commandes_Q1.csv"
q2_path= "commandes_Q2.csv"
clients_path= "clients.csv"
produits_path= "produits.csv"


def extract(q1_path, q2_path, clients_path, produits_path) -> dict:

    logging.info("Chargement des fichiers CSV")
    df_q1 = pd.read_csv(q1_path)
    df_q2 = pd.read_csv(q2_path)
    df_clients = pd.read_csv(clients_path)
    df_produits = pd.read_csv(produits_path)

    logging.info("Rename de la colonne 'moyen_paiement'")
    df_q2 = df_q2.rename(columns={"moyen_paiement":"mode_paiement"})

    logging.info("Ajout de la colonne devise dans Q1")
    df_q1["devise"] = "EUR"

    logging.info("Ajout de la colonne 'source'")
    df_q1["source"] = "Q1_2024"
    df_q2["source"] = "Q2_2024"

    logging.info("Concat Q1 et Q2")
    df_commandes = pd.concat([df_q1, df_q2], ignore_index=True)
  
    logging.info("Création d'un dictionnaire")
    data = {
        "commandes": df_commandes,
        "clients": df_clients,
        "produits": df_produits,
    }

    return data

resultat = extract(q1_path, q2_path, clients_path, produits_path)

18:34:19 - root - INFO - Chargement des fichiers CSV
18:34:19 - root - INFO - Rename de la colonne 'moyen_paiement'
18:34:19 - root - INFO - Ajout de la colonne devise dans Q1
18:34:19 - root - INFO - Ajout de la colonne 'source'
18:34:19 - root - INFO - Concat Q1 et Q2
18:34:19 - root - INFO - Création d'un dictionnaire

---
# 🟡 PARTIE TRANSFORM

### Ex T1 ⭐ — Audit initial
Écris une fonction `audit_dataframe(df, nom)` qui affiche :
- Shape
- Nombre de NaN total et par colonne (en %)
- Nombre de doublons
- Types de chaque colonne

In [14]:
def audit_dataframe(df, nom):
    print(f"Nom du fichier : {nom}")
    print("\nLignes, colonnes", df.shape)
    print("\nPourcentage de NaN : \n", df.isna().mean()* 100)
    print("\nDoublons : ", df.duplicated().sum())
    display('Types de colonnes : ', df.dtypes)

audit_dataframe(df_commandes, "TEST")

Nom du fichier : TEST

Lignes, colonnes (6240, 12)

Pourcentage de NaN :
 commande_id         0.00000
client_id           0.00000
produit_id          0.00000
quantite            0.00000
prix_unitaire       0.00000
montant_total       1.87500
date_commande       0.00000
statut              0.99359
mode_paiement       0.00000
region_livraison    0.00000
devise              0.00000
source              0.00000
dtype: float64

Doublons :  40

'Types de colonnes : '

commande_id          object
client_id            object
produit_id           object
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande        object
statut               object
mode_paiement        object
region_livraison     object
devise               object
source               object
dtype: object

### Ex T2 ⭐ — Supprimer les doublons
Sur le DataFrame consolidé :
1. Détectez et affichez le nombre de doublons
2. Montrez 3 exemples de lignes dupliquées
3. Supprimez les doublons (gardez la première occurrence)
4. Vérifiez qu'il n'en reste plus

In [15]:
df_commandes.duplicated().sum()

np.int64(40)

In [16]:
doublons = df_commandes[df_commandes.duplicated()].head(3)
doublons

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
3000,CMD-Q1-02950,CLI0271,PRD0124,2,55.52,111.04,2024-02-27,annulée,CB,Île-de-France,EUR,Q1_2024
3001,CMD-Q1-00072,CLI0001,PRD0027,7,45.84,320.88,2024-03-20,en_cours,CB,Île-de-France,EUR,Q1_2024
3002,CMD-Q1-00145,CLI0441,PRD0020,9,304.72,2742.48,2024-02-19,livrée,CB,Île-de-France,EUR,Q1_2024

In [17]:
df_commandes = df_commandes.drop_duplicates()

In [18]:
df_commandes.duplicated().sum()

np.int64(0)

### Ex T3 ⭐ — Corriger les types
1. Convertissez `date_commande` en datetime en gérant les formats incohérents
2. Extrayez : `annee`, `mois`, `trimestre`, `jour_semaine`
3. Convertissez `quantite` en numérique avec gestion des erreurs
4. Affichez les types avant et après

In [19]:
df_commandes.dtypes

commande_id          object
client_id            object
produit_id           object
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande        object
statut               object
mode_paiement        object
region_livraison     object
devise               object
source               object
dtype: object

In [20]:
df_commandes['date_commande'].head(2)

0    2024-03-18
1    2024-01-23
Name: date_commande, dtype: object

In [21]:
df_commandes["date_commande"] = pd.to_datetime(df_commandes["date_commande"], format='ISO8601')

In [22]:
df_commandes['annees'] = (df_commandes['date_commande'].dt.year)

In [23]:
df_commandes['mois'] = (df_commandes['date_commande'].dt.month)

In [24]:
df_commandes['trimestre'] = (df_commandes['date_commande'].dt.quarter)

In [25]:
df_commandes['jour_semaine'] = (df_commandes['date_commande'].dt.dayofweek)

In [26]:
df_commandes['quantite'].head(2)

0    1
1    5
Name: quantite, dtype: int64

In [27]:
df_commandes['quantite'].value_counts()

quantite
4    719
2    694
6    693
3    691
8    690
1    682
9    678
7    666
5    658
0     29
Name: count, dtype: int64

In [28]:
df_commandes['quantite'] = df_commandes['quantite'].astype(float)

In [29]:
df_commandes.dtypes

commande_id                 object
client_id                   object
produit_id                  object
quantite                   float64
prix_unitaire              float64
montant_total              float64
date_commande       datetime64[ns]
statut                      object
mode_paiement               object
region_livraison            object
devise                      object
source                      object
annees                       int32
mois                         int32
trimestre                    int32
jour_semaine                 int32
dtype: object

### Ex T4 ⭐⭐ — Traiter les NaN
Pour chaque colonne avec des NaN, choisissez et appliquez la stratégie adaptée :
- `montant_total` NaN → recalculer depuis `quantite × prix_unitaire`
- `statut` NaN → valeur par défaut `'inconnu'`
- `date_commande` NaT → supprimer la ligne (donnée critique)

Justifiez chaque choix dans un commentaire.

In [30]:
df_commandes.head(2)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source,annees,mois,trimestre,jour_semaine
0,CMD-Q1-00001,CLI0496,PRD0081,1.0,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024,2024,3,1,0
1,CMD-Q1-00002,CLI0305,PRD0058,5.0,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024,2024,1,1,1

In [31]:
df_commandes['montant_total'].isna().sum()

np.int64(117)

In [32]:
df_commandes['montant_total'].fillna(df_commandes['quantite'] * df_commandes['prix_unitaire'], inplace=True)

C:\Users\hasss\AppData\Local\Temp\ipykernel_28032\3064975405.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_commandes['montant_total'].fillna(df_commandes['quantite'] * df_commandes['prix_unitaire'], inplace=True)

In [33]:
df_commandes['montant_total'].isna().sum()

np.int64(0)

In [34]:
df_commandes['statut'].isna().sum()

np.int64(62)

In [35]:
df_commandes["statut"] = df_commandes["statut"].fillna("inconnu")

In [36]:
df_commandes['statut'].isna().sum()

np.int64(0)

In [37]:
df_commandes['date_commande'].isna().sum()

np.int64(0)

In [38]:
# Pour supprimer les NaT :
#               df_commandes.dropna(subset=['date_commande'])
# Mais je n'ai pas trouver de NaT

### Ex T5 ⭐⭐ — Détecter et traiter les aberrants
1. Détectez les prix négatifs → supprimez ces lignes
2. Détectez les quantités nulles ou négatives → supprimez
3. Vérifiez la cohérence `montant_total = quantite × prix_unitaire` → corrigez les incohérences
4. Affichez un résumé des corrections effectuées

In [39]:
df_commandes.head(3)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source,annees,mois,trimestre,jour_semaine
0,CMD-Q1-00001,CLI0496,PRD0081,1.0,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024,2024,3,1,0
1,CMD-Q1-00002,CLI0305,PRD0058,5.0,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024,2024,1,1,1
2,CMD-Q1-00003,CLI0044,PRD0128,7.0,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q1_2024,2024,1,1,0

In [40]:
# 1. Détectez les prix négatifs → supprimez ces lignes

df_commandes['prix_unitaire'].value_counts()

prix_unitaire
 71.91     72
 52.42     59
 54.70     55
 82.62     55
 101.48    55
           ..
-793.25     1
-37.93      1
-126.77     1
-65.78      1
-126.57     1
Name: count, Length: 172, dtype: int64

In [41]:
df_commandes = df_commandes[df_commandes['prix_unitaire'] >= 0]

In [42]:
# 2. Détectez les quantités nulles ou négatives → supprimez

df_commandes['quantite'].value_counts()

quantite
4.0    716
2.0    691
6.0    689
3.0    688
8.0    686
1.0    681
9.0    678
7.0    664
5.0    656
0.0     29
Name: count, dtype: int64

In [43]:
df_commandes = df_commandes[df_commandes['quantite'] > 0]

In [44]:
# 3. Vérifiez la cohérence `montant_total = quantite × prix_unitaire` → corrigez les incohérences

df_commandes['montant_attendu'] = df_commandes['quantite'] * df_commandes['prix_unitaire']

In [45]:
# Détection des incohérences avec une tolérance dans les décimales

inco = ~np.isclose(df_commandes['montant_total'], df_commandes['montant_attendu'])

In [46]:
# 4. Affichez un résumé des corrections effectuées

# Plus de prix_unitaire négatifs

df_commandes['prix_unitaire'].value_counts()

prix_unitaire
71.91     72
52.42     59
82.62     55
101.48    55
163.48    54
          ..
106.11    29
29.83     28
237.06    27
308.27    25
55.03     20
Name: count, Length: 151, dtype: int64

In [47]:
# Plus de quantite nulle

df_commandes['quantite'].value_counts()

quantite
4.0    716
2.0    691
6.0    689
3.0    688
8.0    686
1.0    681
9.0    678
7.0    664
5.0    656
Name: count, dtype: int64

In [48]:
# Pas d'incohérence majeure dans le montant_total

df_commandes[inco].head()

Empty DataFrame
Columns: [commande_id, client_id, produit_id, quantite, prix_unitaire, montant_total, date_commande, statut, mode_paiement, region_livraison, devise, source, annees, mois, trimestre, jour_semaine, montant_attendu]
Index: []

### Ex T6 ⭐⭐ — Jointures avec les référentiels
1. Nettoyez `df_clients` (doublons sur `client_id`)
2. Filtrez `df_produits` pour ne garder que les produits actifs
3. Faites un LEFT JOIN commandes ← clients (colonnes : ville, region, segment)
4. Faites un LEFT JOIN commandes ← produits (colonnes : nom, categorie, fournisseur)
5. Vérifiez le nombre de lignes avant et après (doit être identique avec LEFT JOIN)

In [49]:
# 1. Nettoyez `df_clients` (doublons sur `client_id`)

csv_client = "clients.csv"

df_clients = pd.read_csv(csv_client)
df_clients.head(1)

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CLI0001,Client_1,client1@email.fr,Toulouse,Auvergne-RA,Startup,2021-02-01,129.67,True

In [50]:
doublons_clients = df_clients[df_clients.duplicated(keep=False)].head(3)
doublons_clients

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
13,CLI0014,Client_14,client14@email.fr,Marseille,Occitanie,Startup,2022-06-01,317.70,False
32,CLI0033,Client_33,client33@email.fr,Nantes,PACA,Startup,2020-12-02,10689.65,True
40,CLI0041,Client_41,client41@email.fr,Lille,Île-de-France,Grand Compte,2020-10-03,1499.42,False

In [51]:
# Suppression des doublons

df_clients = df_clients.drop_duplicates()

In [52]:
# 2. Filtrez `df_produits` pour ne garder que les produits actifs

csv_produits = "produits.csv"

df_produits = pd.read_csv(csv_produits)
df_produits.head(1)

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True

In [53]:
df_produits.shape

(152, 7)

In [54]:
df_produits.dtypes

produit_id        object
nom               object
categorie         object
prix_unitaire    float64
stock              int64
fournisseur       object
actif               bool
dtype: object

In [55]:
df_produits[df_produits['actif'] == True]

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True
1,PRD0002,Produit_Inf_2,Informatique,135.96,102,MediaShop,True
3,PRD0004,Produit_Inf_4,Informatique,42.82,151,DataStore,True
4,PRD0005,Produit_Inf_5,Informatique,95.95,413,MediaShop,True
5,PRD0006,Produit_Inf_6,Informatique,79.23,191,ElecPlus,True
...,...,...,...,...,...,...,...
145,PRD0146,Produit_Rés_146,Réseau,30.77,367,TechPro,True
146,PRD0147,Produit_Rés_147,Réseau,56.16,99,ElecPlus,True
149,PRD0150,Produit_Rés_150,Réseau,81.48,338,MediaShop,True
150,PRD0151,Produit_Rés_151,Réseau,221.15,468,ElecPlus,True
151,PRD0152,Produit_Rés_152,Réseau,499.98,150,ElecPlus,True

In [56]:
df_commandes.shape

(6149, 17)

In [57]:
# 3. Faites un LEFT JOIN commandes ← clients (colonnes : ville, region, segment) (je rajoute date_inscription pour la q.5 du T7)

df_commandes = pd.merge(df_commandes,
         df_clients[['client_id', 'ville', 'region', 'segment', 'date_inscription']],
         how="left",
         on = "client_id")

In [58]:
# 4. Faites un LEFT JOIN commandes ← produits (colonnes : nom, categorie, fournisseur)

df_commandes = pd.merge(df_commandes,
         df_produits[['produit_id', 'nom', 'categorie', 'fournisseur']],
         how="left",
         on = "produit_id")

In [59]:
df_commandes.shape

(6149, 24)

### Ex T7 ⭐⭐ — Feature Engineering
Créez les colonnes suivantes :
1. `tranche_montant` : `<100€` / `100-500€` / `500-2000€` / `>2000€` avec `pd.cut()`
2. `saison` : depuis le mois (Hiver/Printemps/Été/Automne)
3. `est_annulee` : booléen True si statut == 'annulée'
4. `ca_perdu` : montant_total si commande annulée, sinon 0
5. `delai_inscription_commande` : nb de jours entre date_inscription du client et date_commande

Affichez `value_counts()` pour les colonnes catégorielles créées.

In [60]:
df_commandes.head(1)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,...,trimestre,jour_semaine,montant_attendu,ville,region,segment,date_inscription,nom,categorie,fournisseur
0,CMD-Q1-00001,CLI0496,PRD0081,1.0,49.36,49.36,2024-03-18,annulée,CB,Occitanie,...,1,0,49.36,Marseille,PACA,Particulier,2021-07-26,Produit_Acc_81,Accessoires,ElecPlus

In [61]:
# 1. `tranche_montant` : `<100€` / `100-500€` / `500-2000€` / `>2000€` avec `pd.cut()`

df_commandes['tranche_montant'] = pd.cut(
    df_commandes['montant_total'],
    bins=[0, 100, 500, 2000, 10000],       
    labels=['Petit', 'Moyen', 'Grand', 'Très grand']
)

In [62]:
# 2. `saison` : depuis le mois (Hiver/Printemps/Été/Automne)

def saison(mois):
    if mois in [12, 1, 2]:
        return 'Hiver'
    elif mois in [3, 4, 5]:
        return 'Printemps'
    elif mois in [6, 7, 8]:
        return 'Été'
    else:
        return 'Automne'

df_commandes['saison'] = df_commandes['mois'].apply(saison)

In [63]:
# 3. `est_annulee` : booléen True si statut == 'annulée'

df_commandes['est_annulee'] = df_commandes['statut'] == 'annulée'

In [64]:
# 4. `ca_perdu` : montant_total si commande annulée, sinon 0

df_commandes['ca_perdu'] = np.where(df_commandes['est_annulee'], df_commandes['montant_total'], 0)

In [65]:
# 5. `delai_inscription_commande` : nb de jours entre date_inscription du client et date_commande

df_commandes.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison', 'devise', 'source', 'annees', 'mois', 'trimestre',
       'jour_semaine', 'montant_attendu', 'ville', 'region', 'segment',
       'date_inscription', 'nom', 'categorie', 'fournisseur',
       'tranche_montant', 'saison', 'est_annulee', 'ca_perdu'],
      dtype='object')

In [66]:
df_commandes["date_inscription"] = pd.to_datetime(df_commandes["date_inscription"], format='ISO8601')

In [67]:
df_commandes['delai_inscription_commande'] = df_commandes['date_commande'] - df_commandes['date_inscription']

### Ex T8 ⭐⭐⭐ — Validation qualité
Écris une fonction `valider_pipeline(df) -> bool` qui :
1. Vérifie qu'il n'y a plus de NaN sur les colonnes critiques
2. Vérifie qu'il n'y a plus de doublons
3. Vérifie que tous les prix sont > 0
4. Vérifie que toutes les quantités sont > 0
5. Vérifie que montant_total == quantite × prix_unitaire (à 1 centime près)
6. Retourne True si tout est OK, False sinon avec les erreurs détaillées

In [68]:
def valider_pipeline(df) -> bool :

    erreurs = []

    # Verif NaN
    if df[['montant_total', 'statut', 'date_commande']].isna().sum().sum() > 0 :
        erreurs.append("NaN détectés")

    # Verif Doublons
    if df.duplicated().sum() > 0 :
        erreurs.append("Doublons détectés")

    # Verif prix positif
    if (df['prix_unitaire'] <= 0).sum() > 0:
        erreurs.append("Prix négatifs détectés")


    # Verif quantité positive
    if (df['quantite'] <= 0).sum() > 0:
        erreurs.append("Quantités négatives détectées")


    # Verif montant_total == quantite x prix_unitaire
    if (~np.isclose(df['montant_total'], df['quantite'] * df['prix_unitaire'], atol=0.01)).sum() > 0:
        erreurs.append("Incohérences sur montant_total")

    # Résultats de la validation qualités
    if erreurs:                   
        for e in erreurs:          
            print(e)               
        return False  

    print("Pipeline valide")
    
    return True

In [69]:
# Test de la fonction

valider_pipeline(df_commandes)

Pipeline valide

True

In [70]:
# Test de la fonction

df_test = df_commandes.copy()
df_test.loc[0, 'prix_unitaire'] = -5
valider_pipeline(df_test)

Prix négatifs détectés
Incohérences sur montant_total

False

### Ex T9 ⭐⭐⭐ — Analyse métier post-transform
Maintenant que les données sont propres, répondez en code :
1. Quel est le CA total du S1 2024 ?
2. Quel trimestre a le CA le plus élevé ?
3. Quelle région génère le plus de CA ?
4. Quel segment client est le plus rentable ?
5. Quelle catégorie de produit a le taux d'annulation le plus élevé ?
6. Quel est le CA perdu sur les annulations ?

In [71]:
df_commandes.head(1)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,...,segment,date_inscription,nom,categorie,fournisseur,tranche_montant,saison,est_annulee,ca_perdu,delai_inscription_commande
0,CMD-Q1-00001,CLI0496,PRD0081,1.0,49.36,49.36,2024-03-18,annulée,CB,Occitanie,...,Particulier,2021-07-26,Produit_Acc_81,Accessoires,ElecPlus,Petit,Printemps,True,49.36,966 days

In [72]:
df_commandes.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison', 'devise', 'source', 'annees', 'mois', 'trimestre',
       'jour_semaine', 'montant_attendu', 'ville', 'region', 'segment',
       'date_inscription', 'nom', 'categorie', 'fournisseur',
       'tranche_montant', 'saison', 'est_annulee', 'ca_perdu',
       'delai_inscription_commande'],
      dtype='object')

In [73]:
# 1. Quel est le CA total du S1 2024 ?

s1_2024 = df_commandes[ (df_commandes['annees'] == 2024) & (df_commandes['mois'].isin([1, 2, 3, 4, 5, 6])) & (df_commandes['est_annulee'] == False)]

CA_s1_2024 = s1_2024['montant_total'].sum()
print(CA_s1_2024)

3629611.26

In [74]:
# 2. Quel trimestre a le CA le plus élevé ?

CA_trimestre = df_commandes[df_commandes['est_annulee'] == False].groupby('trimestre')['montant_total'].sum()

print(CA_trimestre)

trimestre
1    1736404.39
2    1893206.87
Name: montant_total, dtype: float64

In [75]:
# 3. Quelle région génère le plus de CA ?

CA_region = df_commandes[df_commandes['est_annulee'] == False].groupby('region')['montant_total'].sum()

print(CA_region)

region
Auvergne-RA           681984.89
Nouvelle-Aquitaine    850817.02
Occitanie             653055.82
PACA                  771653.08
Île-de-France         639909.62
Name: montant_total, dtype: float64

In [76]:
# 4. Quel segment client est le plus rentable ?

segment_rent = df_commandes[df_commandes['est_annulee'] == False].groupby('segment')['montant_total'].sum()

print(segment_rent)

segment
Grand Compte     414379.73
PME              927793.06
Particulier     1911646.78
Startup          343600.86
Name: montant_total, dtype: float64

In [77]:
# 5. Quelle catégorie de produit a le taux d'annulation le plus élevé ?

cat_pro_anul = df_commandes[df_commandes['est_annulee'] == True].groupby('categorie')["est_annulee"].value_counts()
cat_pro_anul

categorie     est_annulee
Accessoires   True            94
Audio         True            78
Informatique  True            92
Réseau        True           128
Stockage      True           104
Téléphonie    True           109
Name: count, dtype: int64

In [78]:
# 6. Quel est le CA perdu sur les annulations ?

ca_perdu_annul = df_commandes['ca_perdu'].sum()
ca_perdu_annul

np.float64(407523.52)

---
# 🔵 PARTIE LOAD

### Ex L1 ⭐ — Export CSV
1. Exportez le DataFrame enrichi en CSV dans `../output/commandes_enrichies.csv`
2. Vérifiez la taille du fichier en Ko
3. Rechargez le CSV et vérifiez que le shape est identique

In [79]:
# 1. Exportez le DataFrame enrichi en CSV dans `../output/commandes_enrichies.csv`

df_commandes.to_csv('commandes_enrichies.csv', index=False)

In [80]:
# 2. Vérifiez la taille du fichier en Ko

# Taille du fichier : 1354 Ko

In [81]:
# 3. Rechargez le CSV et vérifiez que le shape est identique

csv_comm_enrichies = "commandes_enrichies.csv"

commandes_enrichies = pd.read_csv(csv_comm_enrichies)
commandes_enrichies.shape

(6149, 29)

In [82]:
df_commandes.shape

(6149, 29)

### Ex L2 ⭐⭐ — Export Parquet
1. Exportez en Parquet dans `../output/commandes_S1.parquet`
2. Comparez la taille CSV vs Parquet
3. Rechargez le Parquet et vérifiez le shape
4. Mesurez le temps de lecture CSV vs Parquet avec `%%time`

In [83]:
# 1. Exportez en Parquet dans `../output/commandes_S1.parquet`

df_commandes.to_parquet('commandes_S1.parquet', index=False)

In [84]:
# 2. Comparez la taille CSV vs Parquet

# Taille du fichier : 188 Ko

In [85]:
# 3. Rechargez le Parquet et vérifiez le shape

parquet_comm_enrichies = "commandes_S1.parquet"

par_commandes_enrichies = pd.read_parquet(parquet_comm_enrichies)
par_commandes_enrichies.shape

(6149, 29)

In [86]:
# 4. Mesurez le temps de lecture CSV vs Parquet avec `%%time`

%time commandes_enrichies = pd.read_csv(csv_comm_enrichies)

CPU times: total: 31.2 ms
Wall time: 33.9 ms

In [87]:
%time par_commandes_enrichies = pd.read_parquet(parquet_comm_enrichies)

CPU times: total: 0 ns
Wall time: 12 ms

### Ex L3 ⭐⭐ — SQLite
1. Créez une base SQLite `../output/ecommerce.db`
2. Chargez le DataFrame dans une table `commandes`
3. Créez une deuxième table `reporting` avec un agrégat par trimestre et région
4. Exécutez au moins 3 requêtes SQL directement depuis Python et affichez les résultats

In [88]:
# 1. Créez une base SQLite `../output/ecommerce.db`

import sqlite3

connexion = sqlite3.connect("ecommerce.db")

In [89]:
# 2. Chargez le DataFrame dans une table `commandes`

df_commandes.to_sql("commandes", connexion, if_exists="replace", index=False)

C:\Users\hasss\AppData\Local\Temp\ipykernel_28032\3724754438.py:3: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df_commandes.to_sql("commandes", connexion, if_exists="replace", index=False)

6149

In [90]:
df_commandes.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison', 'devise', 'source', 'annees', 'mois', 'trimestre',
       'jour_semaine', 'montant_attendu', 'ville', 'region', 'segment',
       'date_inscription', 'nom', 'categorie', 'fournisseur',
       'tranche_montant', 'saison', 'est_annulee', 'ca_perdu',
       'delai_inscription_commande'],
      dtype='object')

In [91]:
# 3. Créez une deuxième table `reporting` avec un agrégat par trimestre et région

reporting = (df_commandes.groupby(["trimestre", "region"]).agg(chiffre_affaires=("montant_total", "sum"),
                                                                nombre_commandes=("commande_id", "count")).reset_index())

reporting.head()

   trimestre              region  chiffre_affaires  nombre_commandes
0          1         Auvergne-RA         344987.30               545
1          1  Nouvelle-Aquitaine         464522.06               689
2          1           Occitanie         350038.40               547
3          1                PACA         426960.22               652
4          1       Île-de-France         338007.14               527

In [92]:
reporting.to_sql("reporting", connexion, if_exists="replace", index=False)

10

In [93]:
reporting.columns

Index(['trimestre', 'region', 'chiffre_affaires', 'nombre_commandes'], dtype='object')

In [94]:
# 4. Exécutez au moins 3 requêtes SQL directement depuis Python et affichez les résultats

pd.read_sql("""SELECT nom, prix_unitaire, statut, ville
                FROM commandes
                LIMIT 5;
                """, connexion)

               nom  prix_unitaire    statut        ville
0   Produit_Acc_81          49.36   annulée    Marseille
1   Produit_Aud_58         118.62    livrée       Nantes
2  Produit_Rés_128          99.94    livrée       Nantes
3   Produit_Aud_61          75.83   annulée         Lyon
4   Produit_Tél_40          71.91  en_cours  Montpellier

In [95]:
# Top 5 des Produits les plus commandés

pd.read_sql("""SELECT nom as Nom_produit, COUNT(commande_id) as Nombre_commande
                FROM commandes 
                GROUP BY Nom_produit
                ORDER BY Nombre_commande DESC
                LIMIT 5;
                """, connexion)

       Nom_produit  Nombre_commande
0  Produit_Sto_106               59
1  Produit_Sto_113               55
2  Produit_Sto_107               55
3  Produit_Sto_105               54
4  Produit_Rés_136               54

In [96]:
# Top 5 des région les plus rentable

pd.read_sql("""SELECT region as Région, sum(chiffre_affaires) as CA, sum(nombre_commandes) as nombre_commandes
                FROM reporting
                GROUP BY region
                ORDER BY CA DESC
                LIMIT 5;
                """, connexion)

               Région         CA  nombre_commandes
0  Nouvelle-Aquitaine  940282.67              1398
1                PACA  856756.34              1333
2         Auvergne-RA  756578.35              1157
3           Occitanie  730909.80              1133
4       Île-de-France  718095.93              1077

### Ex L4 ⭐⭐⭐ — Parquet partitionné
Exportez le DataFrame en Parquet partitionné par `trimestre` et `region_livraison`.

Puis répondez :
- Combien de fichiers Parquet sont créés ?
- Quelle est la taille totale vs le Parquet non partitionné ?
- Quel est l'avantage du partitionnement pour PySpark ?

---
# 🔴 PIPELINE COMPLET

### Ex P1 ⭐⭐ — Pipeline modulaire
Écris 3 fonctions séparées :
- `extract(data_dir) -> dict`
- `transform(sources: dict) -> pd.DataFrame`
- `load(df, output_dir) -> None`

Chacune doit avoir une docstring et des logs.
Teste chaque fonction indépendamment.

In [97]:
# Fontion Extract

# Configuration de base :
logging.basicConfig(level=logging.INFO,format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",datefmt="%H:%M:%S",force=True,)
logger = logging.getLogger("ETL")

dossier_sources = r"C:\Users\hasss\Desktop\Data_Engineer\Semaine_1_Pandas_Streamlit_Seaborn\Pandas\Pandas\Exercice_09_07_26\dossier_sources"

def extract_2(data_dir = "dossier_sources") -> dict:

    """Extrait et nettoie les fichiers CSV de commandes, clients et produits.

    Lit les 4 fichiers sources, applique les transformations de colonnes
    nécessaires sur Q1/Q2, puis concatène les commandes avant d'en faire un dictionnaire.

    Parameters
    ----------
    data_dir : str, default "dossier_sources"
        Le dossier où se trouvent les CSV.

    Returns
    -------
    dict
        Dictionnaire contenant les DataFrames 'commandes', 'clients' et 'produits'.
    """

    # Construction des chemins
    q1_path = f"{data_dir}/commandes_Q1.csv"
    q2_path = f"{data_dir}/commandes_Q2.csv"
    clients_path = f"{data_dir}/clients.csv"
    produits_path = f"{data_dir}/produits.csv"

    logger.info("Chargement des fichiers CSV")
    df_q1 = pd.read_csv(q1_path)
    df_q2 = pd.read_csv(q2_path)
    df_clients = pd.read_csv(clients_path)
    df_produits = pd.read_csv(produits_path)

    logger.info("Rename de la colonne 'moyen_paiement'")
    df_q2 = df_q2.rename(columns={"moyen_paiement": "mode_paiement"})

    logger.info("Ajout de la colonne devise dans Q1")
    df_q1["devise"] = "EUR"

    logger.info("Ajout de la colonne 'source'")
    df_q1["source"] = "Q1_2024"
    df_q2["source"] = "Q2_2024"

    logger.info("Concat Q1 et Q2")
    df_commandes = pd.concat([df_q1, df_q2], ignore_index=True)

    logger.info("Création d'un dictionnaire")
    dict_data = {
        "commandes": df_commandes,
        "clients": df_clients,
        "produits": df_produits,
    }

    return dict_data

data_dict = extract_2()

18:34:20 - ETL - INFO - Chargement des fichiers CSV
18:34:20 - ETL - INFO - Rename de la colonne 'moyen_paiement'
18:34:20 - ETL - INFO - Ajout de la colonne devise dans Q1
18:34:20 - ETL - INFO - Ajout de la colonne 'source'
18:34:20 - ETL - INFO - Concat Q1 et Q2
18:34:20 - ETL - INFO - Création d'un dictionnaire

In [98]:
# Fonction Transform

def transform(sources : dict) -> pd.DataFrame:

    """Nettoie, enrichit et fusionne les tables commandes, clients et produits.

    Parameters
    ----------
    sources : dict
        Dictionnaire contenant les DataFrames 'commandes', 'clients' et 'produits'.

    Returns
    -------
    pd.DataFrame
        Table consolidée et nettoyée.
    """

    logger.info("Début de transformation")

    # On extrait les csv du dictionnaire
    df_cmd = sources["commandes"].copy()
    df_cli = sources["clients"].copy()
    df_pro = sources["produits"].copy()

    # On supprime les doublons de commandes
    df_cmd = df_cmd.drop_duplicates()
    logger.info("Doublons supprimés dans commandes")

    # Date
    df_cmd["date_commande"] = pd.to_datetime(df_cmd["date_commande"], format='ISO8601')
    df_cmd["annee"] = df_cmd["date_commande"].dt.year
    df_cmd["mois"] = df_cmd["date_commande"].dt.month
    df_cmd["trimestre"] = df_cmd["date_commande"].dt.quarter
    df_cmd["jour_semaine"] = df_cmd["date_commande"].dt.day_name()
    logger.info("Conversion en datetime et nouvelles colonnes (annee, mois, trimestre et jours)")

    # 'quantite en numerique
    df_cmd['quantite'] = df_cmd['quantite'].astype(int)

    # On supprime les prix négatifs et quantités nulles ou négatives
    df_cmd = df_cmd[df_cmd["prix_unitaire"] > 0]
    df_cmd = df_cmd[df_cmd["quantite"] > 0]
    logger.info("Suppression des prix et quantités négatifs")   

    # Gestion des NaN
    df_cmd["statut"] = df_cmd["statut"].fillna("inconnu")
    df_cmd["montant_total"] = df_cmd["montant_total"].fillna(df_cmd["quantite"] * df_cmd["prix_unitaire"])
    logger.info("Remplacement des NaNpar des valeurs")

    # On supprime les doublons dans clients
    df_cli = df_cli.drop_duplicates()
    logger.info("Suppression des doublons dans clients")

    # On garde que les produits actifs
    df_pro = df_pro[df_pro['actif'] == True]
    logger.info("Filtrage des produits actifs")

    # Jointures 
    df_cmd = pd.merge(df_cmd,
         df_cli[['client_id', 'ville', 'region', 'segment', 'date_inscription']],
         how="left",
         on = "client_id")
    logger.info("Jointure del table clients")

    df_cmd = pd.merge(df_cmd,
         df_pro[['produit_id', 'nom', 'categorie', 'fournisseur']],
         how="left",
         on = "produit_id")
    logger.info("Jointure del table produits")

    # On rajoute la colonne tranche_montant
    df_cmd['tranche_montant'] = pd.cut(
    df_cmd['montant_total'],
    bins=[0, 100, 500, 2000, 10000],       
    labels=['Petit', 'Moyen', 'Grand', 'Très grand'])
    logger.info("Ajout de la colonne tranche_montant")


    # On rajoute la colonne saison
    def saison(mois):
        if mois in [12, 1, 2]:
            return 'Hiver'
        elif mois in [3, 4, 5]:
            return 'Printemps'
        elif mois in [6, 7, 8]:
            return 'Été'
        else:
            return 'Automne'

    df_cmd['saison'] = df_cmd['mois'].apply(saison)
    logger.info("Ajout de la colonne saison")

    # On rajoute la colonne est_annulée
    df_cmd['est_annulee'] = df_cmd['statut'] == 'annulée'
    logger.info("Ajout de la colonne 'est_annulée'")

    # On rajoute la colonne ca_perdu
    df_cmd['ca_perdu'] = np.where(df_cmd['est_annulee'], df_cmd['montant_total'], 0)
    logger.info("Ajout de la colonne 'ca_perdu'")

    # On rajoute la colonne date_inscription_commande
    df_cmd["date_inscription"] = pd.to_datetime(df_cmd["date_inscription"], format='ISO8601')
    df_cmd['delai_inscription_commande'] = (df_cmd['date_commande'] - df_cmd['date_inscription']).dt.days
    logger.info("Ajout de la colonne 'date_inscription_commande'")
    
    return df_cmd

In [99]:
df_transform = transform(sources=data_dict)

18:34:20 - ETL - INFO - Début de transformation
18:34:20 - ETL - INFO - Doublons supprimés dans commandes
18:34:20 - ETL - INFO - Conversion en datetime et nouvelles colonnes (annee, mois, trimestre et jours)
18:34:20 - ETL - INFO - Suppression des prix et quantités négatifs
18:34:20 - ETL - INFO - Remplacement des NaNpar des valeurs
18:34:20 - ETL - INFO - Suppression des doublons dans clients
18:34:20 - ETL - INFO - Filtrage des produits actifs
18:34:20 - ETL - INFO - Jointure del table clients
18:34:20 - ETL - INFO - Jointure del table produits
18:34:20 - ETL - INFO - Ajout de la colonne tranche_montant
18:34:20 - ETL - INFO - Ajout de la colonne saison
18:34:20 - ETL - INFO - Ajout de la colonne 'est_annulée'
18:34:20 - ETL - INFO - Ajout de la colonne 'ca_perdu'
18:34:20 - ETL - INFO - Ajout de la colonne 'date_inscription_commande'

In [100]:
df_transform.head(1)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,...,segment,date_inscription,nom,categorie,fournisseur,tranche_montant,saison,est_annulee,ca_perdu,delai_inscription_commande
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,...,Particulier,2021-07-26,NaN,NaN,NaN,Petit,Printemps,True,49.36,966.0

In [103]:
# Fonction Load

def load(df: pd.DataFrame, output_dir: str = "dossier_sources") -> None:

    """Exporte le DataFrame en fichier CSV dans le dossier."""

    logger.info("Début de l'exportation")

    # Load du df
    df.to_csv(f"{output_dir}/commandes_apres_ETL.csv", index=False)

    logger.info(f"Fichier exporté avec succès dans : {output_dir}/commandes_apres_ETL.csv")

In [104]:
load(df_transform)

18:35:42 - ETL - INFO - Début de l'exportation
18:35:42 - ETL - INFO - Fichier exporté avec succès dans : dossier_sources/commandes_apres_ETL.csv

### Ex P2 ⭐⭐⭐ — Pipeline avec gestion d'erreurs
Améliore ton pipeline avec :
1. `try/except` sur chaque étape critique
2. Un log d'erreur détaillé si une étape échoue
3. La pipeline ne doit pas crasher complètement si un fichier est manquant — elle doit logger l'erreur et continuer avec les autres

In [ ]:
# TON CODE ICI

### Ex P3 ⭐⭐⭐ — Tests unitaires du pipeline
Écris 5 tests pour ton pipeline :
1. `test_extract_retourne_4_sources()`
2. `test_transform_supprime_doublons()`
3. `test_transform_pas_de_prix_negatif()`
4. `test_transform_montant_coherent()`
5. `test_load_cree_les_fichiers()`

Chaque test affiche ✅ PASS ou ❌ FAIL.

In [ ]:
# TON CODE ICI

### Ex P4 ⭐⭐⭐⭐ — PROJET FINAL : Pipeline automatisé
Crée un pipeline complet qui :

1. **Détecte automatiquement** tous les fichiers CSV dans `../data_etl/` qui commencent par `commandes_`
2. **Les traite tous** sans avoir à spécifier les chemins manuellement
3. **Génère un rapport HTML** avec :
   - Les statistiques clés (CA, nb commandes, taux annulation)
   - 3 graphiques Plotly intégrés
4. **Sauvegarde** en CSV + Parquet + SQLite
5. **Loggue** chaque étape avec timestamps

C'est exactement ce que vous ferez en PySpark la semaine prochaine, mais à l'échelle de plusieurs To.

📎 Docs utiles :
- [glob — trouver des fichiers](https://docs.python.org/3/library/glob.html)
- [logging](https://docs.python.org/3/library/logging.html)
- [Plotly — export HTML](https://plotly.com/python/interactive-html-export/)

In [ ]:
# TON CODE ICI